### ISSUE TITLE
About contributing a NewRelic sink

### ISSUE THREAD

**Issue by alejandrodnm** [heptiolabs/eventrouter#77]
Hello, I work a New Relic as part of the K8S monitoring team, we would like to contribute a sink that pushes data to our platform, this issue is just to start the conversation and let you know what we have in mind and see if our plans fit the project.

The sink will be pretty simple, it will use the [newrelic sdk](https://github.com/newrelic/infra-integrations-sdk) to push data to an infrastructure agent, meaning that we would have to import the sdk as a dependency.

We would like it to live under it's own directory under the sinks, the reason is that we want to have our own README.md (if we could link it to the root readme it would be awesome) with examples on how to set it up and an example manifest file for installing it. 

For this to work with the infrastructure agent we will need a pod with both the router and the integration, that's why we want to add the example manifest I mentioned before and extend the [helm chart](https://github.com/helm/charts/tree/master/stable/eventrouter) to add this.

Cool project and let me know what you think. cheers.

**Comment by chuckha** [comment]
@timothysc I assigned this to you to make sure it's on your radar. Haven't been following this project much so I'm not sure who the maintainer currently is but I know you can help out here.

**Comment by timothysc** [comment]
I'm ok with it, but please for the love of all that is good in the universe please ensure you don't have massive import dependency sprawl.  Lately every time someone wants to create a new sink, which is really a small piece of code, I get huge import PRs.

**Comment by alejandrodnm** [comment]
thanks for the quick response @chuckha @timothysc and thanks for the green light, we are eager to contribute :) 

@timothysc we'll try to keep it the imports low, I saw the Azure PR D:

![Screenshot 2019-08-13 at 18 10 36](https://user-images.githubusercontent.com/5297542/62957760-ae467100-bdf5-11e9-8cc5-99a2ffcfd3be.png)

**Comment by jorikvdwerf** [comment]
Hey @timothysc  & @chuckha 

As my colleague @alejandrodnm already mentioned, we would like to contribute to this project! 

Before doing so we have some questions about whether our intended changes are OK with you / Heptio.
In short, we would like to make the following changes to the repo:

1. Instead of dep, use go modules, which has been accepted as the community standard
2. Use a multistage Dockerfile to build/test the project (build & test all in a single, easier-to-maintain place. Integrates well with skaffold.dev)
3. For security reasons, use up-to-date versions of:
    - Go: v1.9 -> v1.12.x
    - Alpine Linux: v3.6 -> v3.9.
    - Go dependencies, for example: k8s.io/client_go v5.0.0 -> v12.0.0


It will be quite a large PR, seeing most of the dependencies will be upgraded.

What do you think about these changes? Any concerns/blockers?

Thanks!

**Comment by alejandrodnm** [comment]
Hi, we have decided to go on a different route, either way, thank you very much for being open to our colaborations.

Cheers.
